name: Futter

on: [push]

jobs:
  build:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
          channel: 'stable'
    - run: flutter pub get
    - run: flutter build appbundle
  
  test-job1:
    name: Test widgets
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
          channel: 'stable'
    - run: echo "$FLUTTER_HOME/.pub-cache/bin" >> $GITHUB_PATH
    - run: flutter pub get
    - run: flutter pub global activate junitreport
    - run: flutter test --machine | tojunit -o report.xml
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: report.xml
  
  test-job2:
    name: Test widgets again
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
          channel: 'stable'
    - run: echo "$FLUTTER_HOME/.pub-cache/bin" >> $GITHUB_PATH
    - run: flutter pub get
    - run: flutter pub global activate junitreport
    - run: flutter test --machine | tojunit -o report.xml
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: report.xml
  
  deploy:
    name: Pretend to do deploy
    runs-on: ubuntu-latest
    needs: [test-job1, test-job2]
#     if: always() #for job to run with test-job2 fail
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
          channel: 'stable'
    - run: flutter pub get
    - name: Send notification to Discord
      if: success()
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'Nikita smashes {{ EVENT_PAYLOAD.repository.full_name }}'
